export const jokes = [
  "Why don't scientists trust atoms? Because they make up everything!",
  "Parallel lines have so much in common. It's a shame they'll never meet.",
  "Why did the scarecrow win an award? Because he was outstanding in his field!",
  "How do you organize a space party? You 'planet'!",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "What did one wall say to the other wall? 'I'll meet you at the corner!'",
  "Why did the math book look sad? Because it had too many problems.",
  "I'm reading a book on anti-gravity. It's impossible to put down!",
  "Why did the bicycle fall over? Because it was two-tired!",
  "What do you get when you cross a snowman with a vampire? Frostbite!",
  "How does a penguin build its house? Igloos it together!",
  "What's brown and sticky? A stick!",
  "Why don't skeletons fight each other? They don't have the guts.",
  "I used to play piano by ear, but now I use my hands.",
  "What did one plate say to the other plate? 'Lunch is on me!'",
  "Why don't oysters donate to charity? Because they are shellfish!",
  "Did you hear about the kidnapping at the park? They woke up!",
  "I told my computer I needed a break, and now it won't stop sending me Kit Kat bars!",
  "What's orange and sounds like a parrot? A carrot!",
  "I'm friends with all electricians; we have such good current connections.",
  "I used to be a baker, but I couldn't make enough dough.",
];
